# Generated by Django 3.1.6 on 2021-02-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210206_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('longest_run', models.FloatField(default=0.0)),
                ('longest_ride', models.FloatField(default=0.0)),
            ],
        ),
    ]
