# Generated by Django 3.1.6 on 2021-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_peaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaks',
            name='longest_ride_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peaks',
            name='longest_ride_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peaks',
            name='longest_run_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peaks',
            name='longest_run_local',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
