# Generated by Django 3.1.6 on 2021-02-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20210222_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peaks',
            name='longest_ride_local',
        ),
        migrations.RemoveField(
            model_name='peaks',
            name='longest_run_local',
        ),
    ]
