# Generated by Django 3.1.6 on 2021-02-25 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20210222_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaks',
            name='longest_ride_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='peaks',
            name='longest_run_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
