# Generated by Django 3.1.6 on 2021-03-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20210225_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravatoken',
            old_name='refresh_token',
            new_name='access_token',
        ),
    ]
